package com.oneonezz.three.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.oneonezz.three.greendao.UserPreviewRecord;

import com.oneonezz.three.greendao.db.UserPreviewRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userPreviewRecordDaoConfig;

    private final UserPreviewRecordDao userPreviewRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userPreviewRecordDaoConfig = daoConfigMap.get(UserPreviewRecordDao.class).clone();
        userPreviewRecordDaoConfig.initIdentityScope(type);

        userPreviewRecordDao = new UserPreviewRecordDao(userPreviewRecordDaoConfig, this);

        registerDao(UserPreviewRecord.class, userPreviewRecordDao);
    }
    
    public void clear() {
        userPreviewRecordDaoConfig.clearIdentityScope();
    }

    public UserPreviewRecordDao getUserPreviewRecordDao() {
        return userPreviewRecordDao;
    }

}
