/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oneonezz_jni_JniActivity */

#ifndef _Included_com_oneonezz_jni_JniActivity
#define _Included_com_oneonezz_jni_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oneonezz_jni_JniActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oneonezz_jni_JniActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
